### ISSUE TITLE
Timer covered by stringTest=double

### ISSUE THREAD

**Issue by BryceAG** [phetsims/graphing-lines#52]
Test device:
Bates, Turing

Operating System:
Windows 7 64-bit, OS X 10.9.5

Browser:
FIrefox 42.0, IE 11.0.9600.17843, Chrome 46.0.2490.86 m, Safari 9.0(9537.86.1.56.2)

Problem description:
With stringTest=double and stringTest=long, if the timer is used for the line games, it will be partially covered by the start over button.

Steps to reproduce:
Using either of the string Tests, go to the line game section, and activate the timer. Choose any level of the line game.

Severity:

Screenshots:
![capture](https://cloud.githubusercontent.com/assets/15327201/11286400/fccd85fe-8ed1-11e5-98fc-71cf9c20cb35.PNG)

Troubleshooting information (do not edit):
Name: ‪Graphing Lines‬:‪Graphing Lines‬
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-rc.1/graphing-lines_en.html?stringTest=double
Version: 1.1.0-rc.1 2015-11-16 20:17:53 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
Language: en-US
Window: 1366x631
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"288260a1","branch":"master"},"brand":{"sha":"3b236d6f","branch":"master"},"chipper":{"sha":"6735d265","branch":"master"},"dot":{"sha":"5c39b7d8","branch":"master"},"graphing-lines":{"sha":"6e531507","branch":"1.1"},"joist":{"sha":"2a5b44c4","branch":"master"},"kite":{"sha":"84e84bca","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"61a7c5fa","branch":"master"},"scenery":{"sha":"c0c08ec5","branch":"master"},"scenery-phet":{"sha":"61d8e7ed","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"8d290320","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"},"vegas":{"sha":"03114c7c","branch":"master"},"vibe":{"sha":"40a28182","branch":"master"}}

**Comment by pixelzoom** [comment]
ScoreboardBar (with timer) is a vegas component. I'll check it out.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/tasks/issues/374.

**Comment by pixelzoom** [comment]
ScoreboardBar looks OK with stringTest=long (screenshot below), but has problems with stringTest=double (screenshot above).  This is the culprit line:

`131 maxWidth: screenWidth - leftParentNode.maxWidth // constrain width for i18n`

![screenshot_96](https://cloud.githubusercontent.com/assets/3046552/11404942/fae51b8c-9361-11e5-887e-5c2ad82317d8.png)

**Comment by pixelzoom** [comment]
Ah... The problem occurs when the timer is initially disabled, then enabled.  Since the timer is not visible, I'm guessing that it doesn't affect that initial scaling that results from maxWidth.

**Comment by pixelzoom** [comment]
Fixed in scenery-phet master, screenshots below show stringTest=double and stringTest=long.  This was a trivial fix, so if there are no other common-code issues found, I may branch-and-patch scenery-phet.  Leaving this issues open until RC testing is completed, so I can decide how to proceed.

![screenshot_98](https://cloud.githubusercontent.com/assets/3046552/11405297/22163d42-9364-11e5-9795-bfebebdfd70b.png)
![screenshot_97](https://cloud.githubusercontent.com/assets/3046552/11405308/29026e96-9364-11e5-85cd-a621d4e08ac9.png)

**Comment by pixelzoom** [comment]
Since no other common repo issues have been identified in 1.1.0-rc.1, I'm going to branch-and-patch vegas.

**Comment by pixelzoom** [comment]
vegas has been branched and patched. The branch name is 'graphing-lines-1.1'.

This issue can be verified by spot testing the next RC candidate.

Closing.

**Comment by BryceAG** [comment]
This issue is still present in the new RC test:
![image](https://cloud.githubusercontent.com/assets/15327201/11600483/2d9cc190-9a8a-11e5-9f06-caecf57ae31d.png)

Reopening

**Comment by BryceAG** [comment]
Tested on windows 7, Bates. Both Firefox, Chrome, and Internet Explorer.

**Comment by pixelzoom** [comment]
Ah crap.  The patched branch didn't get into the build, and I tested with stringTest=long (which looks ok).  Please pause testing while I regenerate the RC.

**Comment by pixelzoom** [comment]
Sorry for the hassle Bryce.  Our recent decision to branch-and-patch common repositories (like vegas, which contains the Scoreboard) doesn't work too well with our standard RC build process, and issue which I'll bring up at developer meeting. 

So... Please try it again:

http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-rc.2/graphing-lines_en.html?stringTest=double

Here's what I see:

![screenshot_89](https://cloud.githubusercontent.com/assets/3046552/11600843/8569da64-9a8c-11e5-8841-619ec38f5ca1.png)

**Comment by pixelzoom** [comment]
@BryceAG You may want to clear your browser cache before testing, in case your browser has the previous (broken) version cached.

**Comment by BryceAG** [comment]
The issue has been fixed.

Closing
