### ISSUE TITLE
Assertion failure, two different points are required

### ISSUE THREAD

**Issue by phet-steele** [phetsims/graphing-lines#75]
This can be hit in either graphing-lines or graphing-slope-intercept. @pixelzoom this IS in the current production version (1.1.10).

1. Choose either the Slope-Intercept or Point-Slope screens.
2. Create a line with undefined slope while also placing the y-intercept at 10 or -10.
3. Increment/decrement the rise to get a slope of 0/0:

![gl01](https://cloud.githubusercontent.com/assets/5863899/25152073/178fbc22-2445-11e7-8659-191f0336d639.gif)

Without the interrupting assertion, the points visually overlap:
<img width="1389" alt="screen shot 2017-04-18 at 2 47 54 pm" src="https://cloud.githubusercontent.com/assets/5863899/25152388/0aba9aac-2446-11e7-93de-81462d693eef.png">

(See better assertion at https://github.com/phetsims/graphing-lines/issues/75#issuecomment-294969709)
```
Error: Assertion failed: undefined
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/assert/js/assert.js:21:13)
    at new Line (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/graphing-lines/js/common/model/Line.js?bust=1492509803464:28:15)
    at Function.createPointSlope (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/graphing-lines/js/common/model/Line.js?bust=1492509803464:184:14)
    at Function.createSlopeIntercept (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/graphing-lines/js/common/model/Line.js?bust=1492509803464:193:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/graphing-lines/js/slopeintercept/view/SlopeInterceptEquationNode.js?bust=1492509803464:359:36
    at Array.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/axon/js/Multilink.js?bust=1492509803464:40:18)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/axon/js/Emitter.js?bust=1492509803464:147:49)
    at Property._notifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/axon/js/Property.js?bust=1492509803464:208:29)
    at Property._setAndNotifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/axon/js/Property.js?bust=1492509803464:197:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1492506543283/axon/js/Property.js?bust=1492509803464:141:16)
Approximately 4/18/2017, 3:09:03 AM
```

The assertion in question appears to be:
```
function Line( x1, y1, x2, y2, color ) {
    assert && assert( x1 !== x2 || y1 !== y2 ); // 2 different points are required
    ...
  }
```

Seen on macOS 10.12.4 Chrome. For phetsims/tasks/issues/815 and phetsims/tasks/issues/816.
URL: http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.0-rc.1/graphing-slope-intercept_en.html
Version: 1.0.0-rc.1 2017-04-12 19:48:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"HEAD"},"axon":{"sha":"81919d26","branch":"HEAD"},"babel":{"sha":"fdde4356","branch":"master"},"brand":{"sha":"054ca5c3","branch":"HEAD"},"chipper":{"sha":"36dc0e55","branch":"HEAD"},"dot":{"sha":"a0c5770e","branch":"HEAD"},"graphing-lines":{"sha":"032bc04e","branch":"HEAD"},"graphing-slope-intercept":{"sha":"a851237a","branch":"HEAD"},"joist":{"sha":"91516011","branch":"HEAD"},"kite":{"sha":"81166ce9","branch":"HEAD"},"phet-core":{"sha":"c5c6c2a8","branch":"HEAD"},"phetcommon":{"sha":"68053a7d","branch":"HEAD"},"query-string-machine":{"sha":"d8a4ff18","branch":"HEAD"},"scenery":{"sha":"17b5a7e4","branch":"HEAD"},"scenery-phet":{"sha":"8ea5852c","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"50c6a1d0","branch":"HEAD"},"tandem":{"sha":"18703f2f","branch":"HEAD"},"vegas":{"sha":"3c3561d2","branch":"HEAD"},"vibe":{"sha":"49fdbe7d","branch":"HEAD"}}

**Comment by pixelzoom** [comment]
Impossible for me to tell how or where (which screen) this failure occurred from the above stack trace.

@phet-steele Can you provide any details on how you produced this failure? Were you fuzz testing? Manually testing a specific screen?  Do you have a screenshot showing the sim at time of failure?

**Comment by phet-steele** [comment]
It was automated testing that encountered it while fuzzing. It has been hard for me to reproduce this by hand or outside of automated testing.

**Comment by pixelzoom** [comment]
Could you tell which screen the sim was in when the assertion failed?

**Comment by phet-steele** [comment]
No, this testing is done in a headless chrome browser. I was able to reproduce once with fuzzing, but the sim did not pause on the error....

**Comment by phet-steele** [comment]
Just got a hit with `?screens=1` (so it occurs on the first screen). Sim still didn't pause but here is the stack trace with the new message:
```
Uncaught Error: Assertion failed: points are the same: (0,-10)
    at window.assertions.assertFunction (/assert/js/assert.js:21)
    at new Line (Line.js?bust=1492546286834:30)
    at Function.createPointSlope (Line.js?bust=1492546286834:186)
    at Function.createSlopeIntercept (Line.js?bust=1492546286834:195)
    at SlopeInterceptEquationNode.js?bust=1492546286834:359
    at Array.listener (Multilink.js?bust=1492546286834:40)
    at Emitter.emit2 (Emitter.js?bust=1492546286834:147)
    at Property._notifyObservers (Property.js?bust=1492546286834:208)
    at Property._setAndNotifyObservers (Property.js?bust=1492546286834:197)
    at Property.set (Property.js?bust=1492546286834:141)
    at Array.listener (NumberPicker.js?bust=1492546286834:244)
```

**Comment by pixelzoom** [comment]
Thanks, that helps.  I see you're using master, which now reports the duplicate point value `(0,-10)`, that's super-helpful too.

**Comment by phet-steele** [comment]
@pixelzoom this is easy to reproduce. Expect an issue shortly.

**Comment by phet-steele** [comment]
@pixelzoom I decided to edit the original post instead.

**Comment by phet-steele** [comment]
@pixelzoom, reproducible in 1.0.0........

**Comment by pixelzoom** [comment]
Ah...  The problem is that you shouldn't be able to set the sim in this state.   If the denominator is 0, then the numerator spinner should skip over the zero value.  For example, set the numerator to zero, then observe the behavior of the denominator spinner - it will skip over 0.

**Comment by pixelzoom** [comment]
The same problem occurs in this scenario:

![screenshot_218](https://cloud.githubusercontent.com/assets/3046552/25154650/bd40ebd8-244e-11e7-9470-1cabed08d4fa.png)

So the problem occurs when the intercept is +10 or -10.  The spinner can't skip over the 0, because it would exceed the range of the graph.  The spinners need to be disabled in these situations.

**Comment by pixelzoom** [comment]
This requires being able to customize how `scenery-phet.NumberPicker` decides when to enabled/disable its up/down arrows.  It's currently hardcoded to do so based on the range.

**Comment by pixelzoom** [comment]
I added the required functionality to NumberPicker.  So picking up this fix is going to require updating to scenery-phet master.

**Comment by pixelzoom** [comment]
This problem is also not specific to slope-intercept. Here it is (see below) in point slope.  The fix is the same as described above.

![screenshot_219](https://cloud.githubusercontent.com/assets/3046552/25155987/3e5e10a0-2455-11e7-8785-6889366e4076.png)

**Comment by pixelzoom** [comment]
Fixed in above commit.  @phet-steele could you please verify in master?

**Comment by pixelzoom** [comment]
@phet-steele After verifying, please assign this back to me, do not close.  

I want to investigate whether I should have done this by mutating the `variableRange` Property that is passed to SlopePicker.

**Comment by pixelzoom** [comment]
The answer to my above questions is "no, I should not have fixed this by mutating the `variableRange` Property".   Ranges are not mutated anywhere else in the sim.

**Comment by pixelzoom** [comment]
The answer to my above questions is "no, I should not have fixed this by mutating the `variableRange` Property".   Ranges are not mutated anywhere else in the sim.

So... @phet-steele feel free to close if this verifies OK.

**Comment by phet-steele** [comment]
@pixelzoom The pickers on the the Point-Slope and Slope-Intercept screens have been fixed and I cannot receive this error anymore. I wonder though, for consistency, if the same treatment should be applied to the Slope screen on graphing-lines? I should stress the error CANNOT be hit on this screen anyway, but the pickers still show enabled:

Here the y2 picker should not give me the option to go to ten
<img width="1911" alt="screen shot 2017-04-19 at 11 47 32 am" src="https://cloud.githubusercontent.com/assets/5863899/25194116/a01148d4-24f6-11e7-947e-c79e7973da57.png">

The x1 picker should not let me go to -10
<img width="1512" alt="screen shot 2017-04-19 at 11 47 21 am" src="https://cloud.githubusercontent.com/assets/5863899/25194120/a41395b8-24f6-11e7-8c0e-b8d46a442be7.png">

x2 and y1 pickers behave similarly, I just didn't want to post four screenshots.

**Comment by pixelzoom** [comment]
> x2 and y1 pickers behave similarly, I just didn't want to post four screenshots.

Slacker :)

Good point, i'll check it out.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-lines/issues/75#issuecomment-295010752, I said:
> I want to investigate whether I should have done this by mutating the variableRange Property that is passed to SlopePicker.

Looks like my instincts were correct, but I didn't poke around enough.  The ranges are indeed adjusted dynamically, in `PointSlopeParameterRange`.   I believe this issue should be generally fixed there, and not by adding `upEnabledFunction` and `downEnabledFunction` to `SlopePicker`.

**Comment by pixelzoom** [comment]
Summary of changes:
• reverted the previous changes to `SlopePicker`. 
• modified `PointSlopeParameterRange` to prevent overlap of control points when dynamically adjust ranges. This covers point-slope and slope-intercept forms.
• added `SlopeParameterRange` to dynamically adjust ranges for slope form. This is brand new, ranges were not previously adjusted.

In all cases, pickers should be disabled at the appropriate times, and control points should not overlap.

@phet-steele Would you please verify in master?

**Comment by phet-steele** [comment]
@pixelzoom so close! I can no longer make a zero slope line on any screen if one of the control points in on the bottom or top edge of the graph. For the Slope screen, I can no longer make a line of undefined slope if either control point is on the left or right edge of the graph. Neither the associated picker will allow me to create the line, nor manually manipulating a control point. See in the below video that the rise picker will not let me go to zero, nor can I drag the blue point down.
My struggle:
![gl02](https://cloud.githubusercontent.com/assets/5863899/25287694/98d74304-267f-11e7-8158-c1771c646947.gif)

**Comment by pixelzoom** [comment]
Ah, good catch. 

In the cases we're trying to address, the range should be tweaked only when we're dealing with zero and undefined slopes (rise === 0 and run === 0, respectively).  Fixed in above commit.

@phet-steele back to you.

**Comment by phet-steele** [comment]
@pixelzoom, magnifico.
